# Generated by Django 4.2.11 on 2024-04-12 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=255)),
                ('module_label', models.CharField(max_length=255)),
                ('order', models.FloatField()),
                ('app_visibility', models.BooleanField(default=True)),
                ('web_visibility', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='permissions.module')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=255)),
                ('permission_label', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('requires', models.CharField(blank=True, max_length=255, null=True)),
                ('optional_with', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='permissions.module')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_permissions', to='permissions.permission')),
            ],
        ),
    ]
