# Generated by Django 4.2.11 on 2024-04-12 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technology', '0001_initial'),
        ('designationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empId', models.CharField(max_length=20, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='designationApp.designation')),
                ('technologies', models.ManyToManyField(blank=True, related_name='employees', to='technology.technology')),
            ],
        ),
    ]
