# Generated by Django 4.2.11 on 2024-04-12 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology_stack', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('technology_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology_name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('project_count', models.PositiveIntegerField(default=0)),
                ('technology_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='technology.technologystack')),
            ],
        ),
    ]
